# https://cert-manager.io/docs/concepts/certificate/

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bareena-com-tls
spec:
  secretName: bareena-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: bareena.com
  dnsNames:
    - bareena.com
    - www.bareena.com
