# apiVersion: certmanager.k8s.io/v1alpha1
# kind: Certificate
# metadata:
#   name: bareena-com-tls
# spec:
#   secretName: bareena-com
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: bareena.com
#   dnsNames:
#     - bareena.com
#     - www.bareena.com
#   acme:
#     config:
#       - http01:
#           ingressClass: nginx
#         domains:
#           - bareena.com
#           - www.bareena.com
